config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :productos
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :proveedores
  resources :clientes
  resources :tipo_clientes
  root to: "home#index"
end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id                     :bigint           not null, primary key
#  lote_producto          :string
#  cantidad_producto      :integer
#  unidad_medida_producto :integer
#  fecha_vto_producto     :date
#  proveedor_id           :bigint           not null
#  producto_id            :bigint           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class Stock < ApplicationRecord
  belongs_to :proveedor
  belongs_to :producto

  enum unidad_medida_producto: { unidad: 0, caja: 1, paquete: 2 }

  validates :lote_producto, presence: { message: "Debes ingresar un lote para el producto" }
  validates :cantidad_producto, presence: { message: "Debes ingresar una cantidad para el producto" }
  validates :producto_id, presence: { message: "Debes seleccionar un producto" }
  validates :proveedor_id, presence: { message: "Debes seleccionar un proveedor" }
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock de #{@stock.producto.nombre_producto} modificado satisfactoriamente." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock de #{@stock.producto.nombre_producto} modificado satisfactoriamente." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock removido satisfactoriamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:lote_producto, :cantidad_producto, :unidad_medida_producto, :fecha_vto_producto, :proveedor_id, :producto_id)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<div class="container">
  <%= form_with(model: stock, validate: true) do |form| %>
    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= form.label :producto_id %>
          <%= form.collection_select :producto_id, Producto.select("id, nombre_producto"), :id, :nombre_producto, {prompt: "Seleccione un Producto"}, { class: "form-select" } %>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <%= form.label :lote_producto %>
          <%= form.text_field :lote_producto, class: "form-control" %>
        </div>
      </div> 
    </div>
    <br>
    <div class="row">
      <div class="col">
          <div class="form-group">
            <%= form.label :cantidad_producto %>
            <%= form.number_field :cantidad_producto, class: "form-control", min: 1 %>
          </div>
      </div>
      <div class="col">
        <div class="form-group">
          <%= form.label :unidad_medida_producto %>
          <%= form.select :unidad_medida_producto, Stock.unidad_medida_productos.keys.map { |u| [u.humanize, u] }, {} , {class: "form-select"} %>
        </div>
      </div> 
    </div>
    <br>
    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= form.label :fecha_vto_producto %>
          <%= form.text_field :fecha_vto_producto, type: "date", class: "form-control" %>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <%= form.label :proveedor_id %>
          <%= form.collection_select :proveedor_id, Proveedor.select("id, nombre_proveedor"), :id, :nombre_proveedor, {prompt: "Seleccione un Proveedor"}, { class: "form-select" } %>
        </div>
      </div> 
    </div>  
    <br>
    <div class="actions">
      <%= form.submit "Registrar", class: "btn btn-primary" %>|<%= link_to "Cancelar", stocks_path, class: "btn btn-warning" %>
    </div>
  <% end %>

</div>
  

app/views/stocks/edit.html.erb
<div class="card border-primary">
    <div class="card-header">
        <h3>Editando Stock</h3>    
    </div>
    <div class="card-body">
        <%= render 'form', stock: @stock %>    
    </div>    
</div>

app/views/stocks/index.html.erb
<div class="card border-primary">
  <div class="card-header">
    <h3>Stocks de Productos</h1>  
  </div>
  <div class="card-body">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th class="text-center">Producto</th>
          <th class="text-center">Lote Producto</th>
          <th class="text-center">Cantidad</th>
          <th class="text-center">Unidad de Medida</th>
          <th class="text-center">Fecha de Vencimiento</th>
          <th class="text-center">Proveedor</th>
          <th class="text-center">Opciones</th>
        </tr>
      </thead>

      <tbody>
        <% @stocks.each do |stock| %>
          <tr>
            <td class="text-center"><%= stock.producto.nombre_producto %></td>
            <td class="text-center"><strong><%= stock.lote_producto %></strong></td>
            <td class="text-center"><%= stock.cantidad_producto %></td>
            <td class="text-center"><%= stock.unidad_medida_producto %></td>
            <td class="text-center"><%= formato_fecha stock.fecha_vto_producto %></td>
            <td class="text-center"><%= stock.proveedor.nombre_proveedor %></td>
            <td class="text-center">
              <%= link_to  stock, class: 'btn btn-success btn-sm', "data-toggle" => "tooltip", "data-placement" => "top", title: "Ver Detalles" do %>
                <i class="fas fa-search"></i> 
              <% end %>
              <%= link_to  edit_stock_path(stock), class: 'btn btn-warning btn-sm', "data-toggle" => "tooltip", "data-placement" => "top", title: "Editar" do %>
                <i class="fas fa-pencil-alt"></i> 
              <% end %>
              <%= link_to  stock, method: :delete, data: { confirm: "Estas seguro/a que quierer eliminar?" }, class: 'btn btn-danger btn-sm', "data-toggle" => "tooltip", "data-placement" => "top", title: "Eliminar" do %>
                <i class="fas fa-trash-alt"></i> 
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
  <div class="card-footer">
    <%= link_to 'Nuevo Stock para Producto', new_stock_path, class: "btn btn-primary" %>  
  </div>
</div>

app/views/stocks/new.html.erb
<div class="card border-primary">
    <div class="card-header">
        <h3>Nuevo Stock para Producto</h1>    
    </div>
    <div class="card-body">
        <%= render 'form', stock: @stock %>    
    </div>
</div>

app/views/stocks/show.html.erb
<div class="card">
  <div class="card-header">
    <h4>
      <strong>Lote producto:</strong>
      <%= @stock.lote_producto %>
    -----
      <strong>Producto:</strong>
      <%= @stock.producto.nombre_producto %>
    </p>  
    </h4>  
  </div>
  <div class="card-body">
    <p>
      <strong>Cantidad del Producto:</strong>
      <%= @stock.cantidad_producto %>
    </p>

    <p>
      <strong>Unidad de Medida:</strong>
      <%= @stock.unidad_medida_producto %>
    </p>

    <p>
      <strong>Fecha de Vencimiento:</strong>
      <%= @stock.fecha_vto_producto %>
    </p>

    <p>
      <strong>Proveedor:</strong>
      <%= @stock.proveedor.nombre_proveedor %>
    </p>

  </div>
  <div class="card-footer">
    <%= link_to 'Editar', edit_stock_path(@stock), class: "btn btn-success" %> |
    <%= link_to 'Atràs', stocks_path, class: "btn btn-warning" %>
  </div>
</div>