config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :productos
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :proveedores
  resources :clientes
  resources :tipo_clientes
  root to: "home#index"
end

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
    <script type="text/javascript">
        <% flash.each do |f| %>
            <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
            toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
    </script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light border-3 border-bottom border-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">SISGEVET</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= render 'layouts/navbar_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navbar_links.html.erb
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <% if current_user %>
        <li class="nav-item">
            <%= link_to "Clientes", clientes_path, class: "nav-link #{ active_class?('clientes') }" %>
        </li>
        <li class="nav-item">
            <%= link_to "Proveedores", proveedores_path, class: "nav-link #{ active_class?('proveedores') }" %>
        </li>
        <li class="nav-item">
            <%= link_to "Productos", productos_path, class: "nav-link #{ active_class?('productos') }" %>
        </li>
        <li class="nav-item">
            <%= link_to "Stocks", stocks_path, class: "nav-link #{ active_class?('stocks') }" %>
        </li>
        <li class="nav-item">
            <%= link_to "Tipo de Cliente", tipo_clientes_path, class: "nav-link #{ active_class?('tipo_clientes') }" %>
        </li>
    <% end %>
</ul>
<ul class="navbar-nav my-2 my-sm-0">
    <% if current_user %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Editar usuario", edit_user_registration_path(current_user), class: "dropdown-item" %>
                <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "dropdown-item"  %>
            </ul>
        </li>
    <% else %>
        <%= link_to "Ingresar", new_user_session_path, class: "nav-link" %>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SISGEVET</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "layouts/navbar" %>
      <br>
      <div class="container">
        <%= render "layouts/messages" %>
      </div>
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>